version: '3.8'

services:
  db:
    image: postgres:15
    container_name: calorie_postgres
    restart: always
    environment:
      POSTGRES_DB: calorie_db
      POSTGRES_USER: calorie_user
      POSTGRES_PASSWORD: calorie_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: