# Generated by Django 4.2.23 on 2025-07-20 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
        migrations.AddField(
            model_name='meal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 20, 7, 36, 38, 737516, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
